version: 2
jobs:
  build:
    docker:
      - image: deriv/dzil:latest
        entrypoint: /bin/bash
    steps:
      - checkout
      - run:
          name: Prepare environment
          command: |
            apt-get update
            apt-get -y -q --no-install-recommends install $(cat aptfile)
      - restore_cache:
          keys:
            - cpanfile-{{ arch }}-{{ checksum "cpanfile" }}
      - run:
          name: Install deps
          command: |
            cpanm -l deps --installdeps -n .
      - save_cache:
          key: cpanfile-{{ arch }}-{{ checksum "cpanfile" }}
          paths:
            - deps
      - run:
          name: Run test
          command: |
            # Upstream Pod::Inherit is no longer maintained, we may end up needing
            # to fork this but for now we can patch it out...
            export PERL5LIB=$(pwd)/deps/lib/perl5:$(pwd)/deps/lib/perl5/$(perl -MConfig -le'print $Config{archname}'):$PERL5LIB
            perl -i -lpe's{did_it = \$src \? do \K\$src}{"./\$src"}' /opt/perl-5.32.0/lib/site_perl/5.32.0/Pod/Inherit.pm
            dzil test
      - run:
          name: Author tests
          command: |
            export PERL5LIB=$(pwd)/deps/lib/perl5:$(pwd)/deps/lib/perl5/$(perl -MConfig -le'print $Config{archname}'):$PERL5LIB
            dzil xtest
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
